### ISSUE TITLE
Can't open Search dialog of Many2Many

### ISSUE THREAD

**Issue by Xevib** [gisce/openerp-client-kde#27]
# Description
- Ont the branch `2o3_qt5` can't open the Search dialog because tries to call `save` and `cancel` method

**Comment by XaviTorello** [comment]
Related to #22

**Comment by elpaso** [comment]
Just wondering before I open another ticket, is this the same issue?

```
An error has occurred while executing Python code: 

AttributeError: 'OneToManyFieldWidget' object has no attribute 'save' 
Traceback (most recent call last):
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Fields/AbstractFieldWidget.py", line 123, in showEvent
    self.initGui()
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Fields/OneToMany/OneToMany.py", line 246, in initGui
    'mode', 'tree,form').split(','))
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 195, in setViewTypes
    self.switchView()
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 493, in switchView
    if self.currentView().showsMultipleRecords():
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 766, in currentView
    self.addViewByIdAndType(id, type)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 520, in addViewByIdAndType
    return self.addView(view['arch'], view['fields'], display, toolbar=view.get('toolbar', False), id=view.get('view_id', False))
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 601, in addView
    self.loadActions(toolbar)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Screen.py", line 613, in loadActions
    self.actions = ActionFactory.create(self, actions, self.resource)
  File "/home/ale/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisce/ext-libs/Koo/Screen/Action.py", line 154, in create
    'action': parent.parentWidget().save,
AttributeError: 'OneToManyFieldWidget' object has no attribute 'save'

```
