### ISSUE TITLE
Error in Rpc.py: '_' is not defined

### ISSUE THREAD

**Issue by elpaso** [gisce/openerp-client-kde#44]
```
Traceback (most recent call last):
  File "/home/ale/dev/python/qgisce/ext-libs/Koo/Rpc/Rpc.py", line 311, in call
    self.password, *args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 1: "<type 'exceptions.TypeError'>:cannot marshal <type 'thread.lock'> objects">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ale/dev/python/qgisce/ext-libs/Koo/Rpc/Rpc.py", line 533, in execute
    return self.call(obj, method, *args)
  File "/home/ale/dev/python/qgisce/ext-libs/Koo/Rpc/Rpc.py", line 519, in call
    value = self.connection.call(obj, method, *args)
  File "/home/ale/dev/python/qgisce/ext-libs/Koo/Rpc/Rpc.py", line 318, in call
    raise RpcServerException(err.faultCode, err.faultString)
Koo.Rpc.Rpc.RpcServerException: <type 'exceptions.TypeError'>:cannot marshal <type 'thread.lock'> objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ale/dev/python/qgisce/qgisceutils/session.py", line 196, in discard
    session_object = ERPClient.model(QGISCE_SESSION_MODEL_NAME).browse(session_id)
  File "/home/ale/dev/python/qgisce/ext-libs/Koo/Rpc/Rpc.py", line 547, in execute
    Notifier.notifyError(_('Application Error'), _(
NameError: name '_' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ale/dev/python/qgisce/test/test_session.py", line 104, in test_discard
    self.assertTrue(Session.discard(session_id))
  File "/home/ale/dev/python/qgisce/qgisceutils/session.py", line 199, in discard
    raise SessionDiscardError(str(e))
qgisceutils.session.SessionDiscardError: name '_' is not defined

----------------------------------------------------------------------
```

**Comment by elpaso** [comment]
This is in branch 2to5
